Updated web crawler pipeline to save all downloaded files into default output folder
austinwalter/ai-base pull request #3
Opened 2024-02-03 15:33 UTC by shariful-alam

2024-02-05 17:20 UTC, austinwalter requested changes

2024-02-05 17:20 UTC, austinwalter commented on webcrawler/scraper/output/.keep
What's the `.keep` folder for?

2024-02-05 17:20 UTC, austinwalter commented on webcrawler/scraper/spiders/articles_spider.py
> +        filename = f'scraper/output/article-{page}.html'
Can we move where we set the output path to a different file so that it doesn't have to be set in every spider?

2024-02-05 17:30 UTC, shariful-alam commented on webcrawler/scraper/output/.keep
The `.keep` file is to keep the `output` folder. Otherwise, there's no content inside the output folder. So, to push this folder to git, I had to add this.

2024-02-12 20:06 UTC, austinwalter approved these changes

2024-02-12 20:06 UTC, merged